name: deconvolution
channels:
- defaults
dependencies:
- backports=1.0=py27_0
- decorator=4.0.11=py27_0
- enum34=1.1.6=py27_0
- freetype=2.5.5=2
- get_terminal_size=1.0.0=py27_0
- ipython=5.3.0=py27_0
- ipython_genutils=0.2.0=py27_0
- jpeg=8d=2
- lcms=1.19=0
- libpng=1.6.27=0
- mkl=2017.0.1=0
- numpy=1.12.1=py27_0
- openssl=1.0.2l=0
- path.py=10.3.1=py27_0
- pathlib2=2.2.1=py27_0
- pexpect=4.2.1=py27_0
- pickleshare=0.7.4=py27_0
- pil=1.1.7=py27_2
- pip=9.0.1=py27_1
- prompt_toolkit=1.0.14=py27_0
- ptyprocess=0.5.1=py27_0
- pygments=2.2.0=py27_0
- python=2.7.13=0
- readline=6.2=2
- scandir=1.5=py27_0
- setuptools=27.2.0=py27_0
- simplegeneric=0.8.1=py27_1
- six=1.10.0=py27_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- traitlets=4.3.2=py27_0
- wcwidth=0.1.7=py27_0
- wheel=0.29.0=py27_0
- zlib=1.2.8=3
- pip:
  - backports.shutil-get-terminal-size==1.0.0
  - ipython-genutils==0.2.0
  - prompt-toolkit==1.0.14
